"""R048 — Put/call ratio regime: acceptance tests.

Separate implementation of the §R2 normative pseudocode (hysteresis state
machine). Expected fixture values were generated by an independent generator
(script in /tmp, seed 42048); the pinned-behavior tests below assert the
hysteresis/boundary semantics directly, so agreement is not circular.
Definition of done: `python3 -m pytest modules/tests/test_R048.py -q` exits 0.
"""
import csv
import math
import os

RID = "R048"
TOL = 1e-9            # [default] value tolerance
DUAL_TOL = 1e-12      # [default] dual-estimator agreement tolerance
ESTIMATOR_VERSION = "1.1.0"
CADENCE_NS = 86400000000000
DATA_VINTAGE = "2026-09-09"

CFG = {
    "fear": 1.2,        # [default] entry band for FEAR (inclusive)
    "greed": 0.6,       # [default] entry band for COMPLACENCY (inclusive)
    "hysteresis": 0.1,  # [default] exit offset; entry bands are inclusive
    "stale_days": 3,    # [default] F4 staleness horizon in cadences
    "bounds_hi": 10.0,  # [default] upper bound for a sane daily ratio
    "min_lag_bars": 1,  # [default]
}

COST_ADJUSTMENT_R048 = {
    "regime_id": "R048",
    "version": "1.1.0",
    "FEAR": {"spread_mult": 1.3, "impact_mult": 1.2, "borrow_mult": 1.0,
             "fee_add_bps": 0.0},
    "NORMAL": {"spread_mult": 1.0, "impact_mult": 1.0, "borrow_mult": 1.0,
               "fee_add_bps": 0.0},
    "COMPLACENCY": {"spread_mult": 0.9, "impact_mult": 1.0, "borrow_mult": 1.0,
                    "fee_add_bps": 0.0},
    "tag": "[example]",
}


def _parse_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def _mk(state, value, ts_ns, module_state):
    return {
        "regime_id": RID,
        "state": state,
        "value": value,
        "estimator_version": ESTIMATOR_VERSION,
        "data_vintage": DATA_VINTAGE,
        "computed_at": ts_ns,
        "module_state": module_state,
        "min_lag_bars": CFG["min_lag_bars"],
    }


def _row_value(e, cfg):
    p = _parse_float(e["pcr"])
    if not math.isfinite(p):
        raise ValueError("bad put/call print")  # F1: missing or non-numeric
    return p


def _dual_value(e, cfg):
    """F3 dual estimator: recompute the ratio from raw put/call volumes.

    Raises ValueError when the raw legs are unavailable (feed carries only
    the published ratio), in which case the F3 check is skipped for that row.
    """
    put = _parse_float(e.get("put_vol", ""))
    call = _parse_float(e.get("call_vol", ""))
    if not math.isfinite(put) or not math.isfinite(call) or call <= 0:
        raise ValueError("no raw legs for dual estimator")
    return put / call


def _state_of(pcr, prev, cfg):
    """§R2 hysteresis state machine.

    Hold bands: FEAR holds while pcr >= fear - h (inclusive); COMPLACENCY
    holds while pcr <= greed + h (inclusive). Otherwise stateless entry
    bands: pcr >= fear -> FEAR; pcr <= greed -> COMPLACENCY; else NORMAL.
    Exit is strict on the offset band, so pcr == fear - h still holds FEAR.
    """
    h = cfg["hysteresis"]
    if prev == "FEAR" and pcr >= cfg["fear"] - h:
        return "FEAR"
    if prev == "COMPLACENCY" and pcr <= cfg["greed"] + h:
        return "COMPLACENCY"
    if pcr >= cfg["fear"]:
        return "FEAR"
    if pcr <= cfg["greed"]:
        return "COMPLACENCY"
    return "NORMAL"


def detect(state, events, cfg):
    """detect(state, events, cfg) -> list[RegimeState].

    Causal: the label at position t uses only events[:t+1]. F1 (missing row)
    and F2 (non-finite, non-positive, or out-of-bounds) emit UNKNOWN and leave
    the internal prev-state frozen, so hysteresis resumes correctly when the
    print returns. Corporate-action flags (adj_flag) are ignored: volume
    ratios need no price adjustment. Never interpolates.
    """
    if not events:
        return [_mk("UNKNOWN", float("nan"), 0, "UNKNOWN")]  # F1
    out = []
    prev = (state or {}).get("prev_state", "NORMAL")
    for e in events:
        ts = int(float(e["ts_ns"]))
        try:
            p = _row_value(e, cfg)
        except Exception:
            out.append(_mk("UNKNOWN", float("nan"), ts, "UNKNOWN"))  # F1
            continue
        if not (0.0 < p < cfg["bounds_hi"]):
            out.append(_mk("UNKNOWN", p, ts, "UNKNOWN"))  # F2 bounds
            continue
        st = _state_of(p, prev, cfg)
        prev = st
        out.append(_mk(st, p, ts, "OK"))
    return out


def apply_freshness(rs, now_ns):
    """F4: expire to UNKNOWN when computed_at is older than stale_days x cadence."""
    if rs["computed_at"] and (now_ns - rs["computed_at"]) > CFG["stale_days"] * CADENCE_NS:
        rs = dict(rs)
        rs["module_state"] = "UNKNOWN"
        rs["state"] = "UNKNOWN"
    return rs


def _load(name):
    p = os.path.join(os.path.dirname(__file__), "..", "fixtures", name)
    with open(p) as f:
        lines = [ln for ln in f if not ln.startswith("#")]
    return list(csv.DictReader(lines))


def _type_header(name):
    with open(os.path.join(os.path.dirname(__file__), "..", "fixtures", name)) as f:
        first = f.readline()
    assert first.startswith("# TYPE: validation-run"), f"{name} needs TYPE header"


def _close(a, b, tol):
    if math.isnan(a) or math.isnan(b):
        return math.isnan(a) and math.isnan(b)
    return abs(a - b) <= tol


def _check_tape(tape_name, exp_name):
    _type_header(tape_name)
    tape = _load(tape_name)
    exp = _load(exp_name)
    assert tape and exp, "fixtures must be non-empty"
    got = detect(None, tape, CFG)
    assert len(got) == len(exp), (len(got), len(exp))
    for g, x in zip(got, exp):
        assert g["state"] == x["state"], (g["state"], x["state"])
        assert g["module_state"] == x["module_state"], (g, x)
        xv = _parse_float(x["value"]) if x["value"].strip() else float("nan")
        assert _close(g["value"], xv, TOL), (g["value"], xv)
    return tape, got


def test_fixture_replay():
    _check_tape("R048_tape.csv", "R048_expected.csv")


def test_hysteresis_fixture_replay():
    _check_tape("R048_tape_hysteresis.csv", "R048_expected_hysteresis.csv")


def test_hysteresis_state_transitions():
    """Hold bars must be FEAR/COMPLACENCY where a stateless band map would exit.

    A stateless implementation (no hysteresis) would label bar1 (1.15) and
    bar5 (0.65) NORMAL; the hysteresis machine must hold FEAR/COMPLACENCY.
    Also pins the direct FEAR -> COMPLACENCY transition at bar9.
    """
    tape, got = _check_tape("R048_tape_hysteresis.csv",
                            "R048_expected_hysteresis.csv")
    assert got[1]["state"] == "FEAR", "1.15 must hold FEAR (>= fear-h), stateless says NORMAL"
    assert got[2]["state"] == "FEAR", "1.10 == fear-h holds FEAR (inclusive)"
    assert got[3]["state"] == "NORMAL", "1.099 < fear-h exits FEAR (strict)"
    assert got[5]["state"] == "COMPLACENCY", "0.65 must hold COMPLACENCY (<= greed+h)"
    assert got[6]["state"] == "COMPLACENCY", "0.70 == greed+h holds (inclusive)"
    assert got[7]["state"] == "NORMAL", "0.701 > greed+h exits (strict)"
    assert got[8]["state"] == "FEAR", "1.20 == fear enters FEAR (inclusive)"
    assert got[9]["state"] == "COMPLACENCY", "FEAR -> COMPLACENCY in one bar via fall-through"
    assert got[11]["state"] == "COMPLACENCY", "prev COMPLACENCY resumes after F1 UNKNOWN"


def test_boundary_semantics():
    """Entry inclusive; exit strict on the hysteresis-offset band."""
    fear, greed, h = CFG["fear"], CFG["greed"], CFG["hysteresis"]
    assert _state_of(fear, "NORMAL", CFG) == "FEAR"
    assert _state_of(greed, "NORMAL", CFG) == "COMPLACENCY"
    assert _state_of(fear - h, "FEAR", CFG) == "FEAR"
    assert _state_of(fear - h - 1e-6, "FEAR", CFG) == "NORMAL"
    assert _state_of(greed + h, "COMPLACENCY", CFG) == "COMPLACENCY"
    assert _state_of(greed + h + 1e-6, "COMPLACENCY", CFG) == "NORMAL"
    # bands must not overlap: the hold intervals are disjoint
    assert fear - h > greed + h, "entry/hold bands overlap; recalibrate"


def test_no_lookahead():
    """The label at t must be identical with and without later data."""
    for tape_name in ("R048_tape.csv", "R048_tape_hysteresis.csv"):
        tape = _load(tape_name)
        full = detect(None, tape, CFG)
        for k in range(1, len(tape) + 1):
            prefix = detect(None, tape[:k], CFG)
            assert len(prefix) == k
            for a, b in zip(prefix, full[:k]):
                assert a["state"] == b["state"], (tape_name, k, a, b)
                assert a["module_state"] == b["module_state"]
                assert _close(a["value"], b["value"], TOL), (k, a["value"], b["value"])


def test_f1_missing_input_unknown():
    got = detect(None, [], CFG)
    assert len(got) == 1
    assert got[0]["module_state"] == "UNKNOWN"
    assert got[0]["state"] == "UNKNOWN"
    # mid-tape gap: UNKNOWN emitted, internal state frozen
    tape = _load("R048_tape_hysteresis.csv")
    got = detect(None, tape, CFG)
    assert got[10]["module_state"] == "UNKNOWN"  # empty pcr row
    assert got[10]["state"] == "UNKNOWN"


def test_f2_bounds_violation_unknown():
    tape = _load("R048_tape_hysteresis.csv")
    got = detect(None, tape, CFG)
    assert got[12]["module_state"] == "UNKNOWN" and got[12]["value"] == 0  # non-positive
    assert got[13]["module_state"] == "UNKNOWN"  # > bounds_hi
    bad = [dict(r) for r in _load("R048_tape.csv")]
    bad[0]["pcr"] = "0"
    assert detect(None, bad, CFG)[0]["module_state"] == "UNKNOWN"


def test_f3_dual_estimator_agreement():
    """Recomputed ratio from raw put/call legs must agree with the published print."""
    tape = _load("R048_tape_hysteresis.csv")
    n = 0
    for e in tape:
        try:
            v1 = _row_value(e, CFG)
            v2 = _dual_value(e, CFG)
        except ValueError:
            continue  # F1/F2 row or no raw legs: nothing to check
        if not (0.0 < v1 < CFG["bounds_hi"]):
            continue  # F2 row: both estimators must agree on UNKNOWN-ness
        assert _close(v1, v2, DUAL_TOL), (v1, v2)
        n += 1
    assert n >= 10, f"dual estimator checked too few rows: {n}"


def test_f4_staleness_expires_to_unknown():
    tape = _load("R048_tape.csv")
    rs = detect(None, tape, CFG)[-1]
    assert rs["computed_at"] > 0
    aged = apply_freshness(rs, rs["computed_at"] + (CFG["stale_days"] + 1) * CADENCE_NS)
    assert aged["module_state"] == "UNKNOWN"
    assert aged["state"] == "UNKNOWN"
    fresh = apply_freshness(rs, rs["computed_at"] + CADENCE_NS)
    assert fresh["module_state"] == rs["module_state"]


def test_f5_no_expost_selection():
    assert not hasattr(detect, "select_backtest_periods")
    tape = _load("R048_tape.csv")
    cfg_before = dict(CFG)
    for rs in detect(None, tape, CFG):
        assert rs["min_lag_bars"] >= 1
        assert rs["computed_at"] >= 0
    assert CFG == cfg_before, "detect must not mutate the calibrated config"


def test_spot_handcheck():
    """Independently hand-verified arithmetic (see module section R3)."""
    tape = _load("R048_tape.csv")
    got = detect(None, tape, CFG)
    assert got[0]["state"] == "FEAR"
    assert got[1]["state"] == "NORMAL"
    assert got[2]["state"] == "COMPLACENCY"


def test_emits_regime_state_vector():
    got = detect(None, _load("R048_tape.csv"), CFG)[0]
    assert got["regime_id"] == "R048"
    assert got["estimator_version"] == ESTIMATOR_VERSION
    assert got["data_vintage"] == DATA_VINTAGE
    assert got["computed_at"] > 0
    assert got["min_lag_bars"] == 1
    assert got["module_state"] in ("OK", "DEGRADED", "UNKNOWN", "OFF")


def test_corporate_action_neutral():
    """adj_flag must not change the label: volume ratios need no price adjustment."""
    tape = _load("R048_tape_hysteresis.csv")
    got = detect(None, tape, CFG)
    assert got[14]["state"] == "NORMAL"  # row carries adj_flag='split'
    plain = [dict(r, adj_flag="") for r in tape]
    got2 = detect(None, plain, CFG)
    assert [g["state"] for g in got] == [g["state"] for g in got2]


def test_cost_interface_record():
    """§R5 record: every regime state maps to a complete, sane adjustment."""
    rec = COST_ADJUSTMENT_R048
    assert rec["regime_id"] == "R048"
    assert rec["version"] == "1.1.0"
    assert rec["tag"] == "[example]"
    for st in ("FEAR", "NORMAL", "COMPLACENCY"):
        adj = rec[st]
        for k in ("spread_mult", "impact_mult", "borrow_mult"):
            assert adj[k] > 0, (st, k, adj[k])
        assert adj["fee_add_bps"] >= 0
    # FEAR must widen costs vs NORMAL; NORMAL is the identity record
    assert rec["FEAR"]["spread_mult"] >= rec["NORMAL"]["spread_mult"]
    assert rec["FEAR"]["impact_mult"] >= rec["NORMAL"]["impact_mult"]
    assert rec["NORMAL"]["spread_mult"] == 1.0
    assert rec["NORMAL"]["impact_mult"] == 1.0
